#!/usr/bin/env python3
"""Generate EPUBs using ebooklib (Python).

Creates multiple EPUB variants with different structures and content
to exercise ebooklib's OPF, NCX, and content document generation.

Usage: python3 stress-test/toolchain-epubs/generate-ebooklib.py [OUTPUT_DIR]
"""

import os
import sys

from ebooklib import epub


def create_basic_prose(output_dir):
    """Basic prose EPUB with chapters, formatting, and metadata."""
    book = epub.EpubBook()
    book.set_identifier("urn:uuid:ebooklib-basic-001")
    book.set_title("Basic Prose Document")
    book.set_language("en")
    book.add_author("Test Author")
    book.add_metadata("DC", "description", "A basic prose document generated by ebooklib.")
    book.add_metadata("DC", "publisher", "Test Publisher")

    # CSS
    style = epub.EpubItem(
        uid="style",
        file_name="style/default.css",
        media_type="text/css",
        content=b"body { font-family: serif; line-height: 1.6; }\n"
        b"h1 { text-align: center; }\n"
        b"h2 { border-bottom: 1px solid #ccc; }\n"
        b"code { font-family: monospace; background: #f4f4f4; padding: 2px 4px; }\n",
    )
    book.add_item(style)

    # Chapter 1
    c1 = epub.EpubHtml(title="Introduction", file_name="ch01.xhtml", lang="en")
    c1.content = """<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Introduction</title><link rel="stylesheet" href="style/default.css" type="text/css"/></head>
<body>
<h1>Chapter 1: Introduction</h1>
<p>This is a <strong>basic prose</strong> document generated by <em>ebooklib</em>.</p>
<p>It includes <code>inline code</code>, <a href="https://example.com">links</a>,
and various formatting elements.</p>
<h2>Section 1.1: Lists</h2>
<ul>
<li>First item</li>
<li>Second item with <strong>bold</strong></li>
<li>Third item with <code>code</code></li>
</ul>
<ol>
<li>Step one</li>
<li>Step two</li>
<li>Step three</li>
</ol>
<h2>Section 1.2: Block Elements</h2>
<blockquote><p>The only way to do great work is to love what you do.</p></blockquote>
<pre><code>def fibonacci(n):
    if n &lt;= 1:
        return n
    return fibonacci(n-1) + fibonacci(n-2)
</code></pre>
</body>
</html>"""
    c1.add_item(style)
    book.add_item(c1)

    # Chapter 2
    c2 = epub.EpubHtml(title="Tables and More", file_name="ch02.xhtml", lang="en")
    c2.content = """<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Tables</title><link rel="stylesheet" href="style/default.css" type="text/css"/></head>
<body>
<h1>Chapter 2: Tables and More</h1>
<table>
<thead><tr><th>Name</th><th>Value</th><th>Description</th></tr></thead>
<tbody>
<tr><td>Alpha</td><td>1</td><td>First entry</td></tr>
<tr><td>Beta</td><td>2</td><td>Second entry</td></tr>
<tr><td>Gamma</td><td>3</td><td>Third entry</td></tr>
</tbody>
</table>
<h2>Definition List</h2>
<dl>
<dt>Term One</dt><dd>The definition of term one.</dd>
<dt>Term Two</dt><dd>The definition of term two.</dd>
</dl>
</body>
</html>"""
    c2.add_item(style)
    book.add_item(c2)

    # Chapter 3
    c3 = epub.EpubHtml(title="Conclusion", file_name="ch03.xhtml", lang="en")
    c3.content = """<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Conclusion</title><link rel="stylesheet" href="style/default.css" type="text/css"/></head>
<body>
<h1>Chapter 3: Conclusion</h1>
<p>This chapter wraps up the basic prose document.</p>
<hr/>
<p>The end.</p>
</body>
</html>"""
    c3.add_item(style)
    book.add_item(c3)

    book.toc = [
        epub.Link("ch01.xhtml", "Introduction", "ch01"),
        epub.Link("ch02.xhtml", "Tables and More", "ch02"),
        epub.Link("ch03.xhtml", "Conclusion", "ch03"),
    ]
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = ["nav", c1, c2, c3]

    path = os.path.join(output_dir, "ebooklib-basic-prose.epub")
    epub.write_epub(path, book)
    return path


def create_multilingual(output_dir):
    """Multilingual EPUB with content in several languages."""
    book = epub.EpubBook()
    book.set_identifier("urn:uuid:ebooklib-multilingual-001")
    book.set_title("Multilingual Content Test")
    book.set_language("en")
    book.add_author("Test Author")

    chapters = []

    # English
    c_en = epub.EpubHtml(title="English", file_name="en.xhtml", lang="en")
    c_en.content = """<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head><title>English</title></head>
<body>
<h1>English</h1>
<p>This chapter is written in English with standard prose.</p>
</body>
</html>"""
    book.add_item(c_en)
    chapters.append(c_en)

    # French
    c_fr = epub.EpubHtml(title="Français", file_name="fr.xhtml", lang="fr")
    c_fr.content = """<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
<head><title>Français</title></head>
<body>
<h1>Français</h1>
<p>Ceci est un chapitre en français. Les caractères spéciaux incluent: é, è, ê, ë, à, ç, ô, û.</p>
</body>
</html>"""
    book.add_item(c_fr)
    chapters.append(c_fr)

    # German
    c_de = epub.EpubHtml(title="Deutsch", file_name="de.xhtml", lang="de")
    c_de.content = """<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de">
<head><title>Deutsch</title></head>
<body>
<h1>Deutsch</h1>
<p>Dies ist ein Kapitel auf Deutsch. Besondere Zeichen: ä, ö, ü, ß, Ä, Ö, Ü.</p>
</body>
</html>"""
    book.add_item(c_de)
    chapters.append(c_de)

    # Japanese
    c_ja = epub.EpubHtml(title="日本語", file_name="ja.xhtml", lang="ja")
    c_ja.content = """<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja">
<head><title>日本語</title></head>
<body>
<h1>日本語</h1>
<p>これは日本語で書かれた章です。漢字、ひらがな、カタカナを含みます。</p>
</body>
</html>"""
    book.add_item(c_ja)
    chapters.append(c_ja)

    # Chinese
    c_zh = epub.EpubHtml(title="中文", file_name="zh.xhtml", lang="zh")
    c_zh.content = """<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh">
<head><title>中文</title></head>
<body>
<h1>中文</h1>
<p>这是用中文写的一章。它包含简体中文字符。</p>
</body>
</html>"""
    book.add_item(c_zh)
    chapters.append(c_zh)

    book.toc = [epub.Link(c.file_name, c.title, c.file_name.replace(".xhtml", "")) for c in chapters]
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = ["nav"] + chapters

    path = os.path.join(output_dir, "ebooklib-multilingual.epub")
    epub.write_epub(path, book)
    return path


def create_minimal(output_dir):
    """Minimal EPUB with a single chapter."""
    book = epub.EpubBook()
    book.set_identifier("urn:uuid:ebooklib-minimal-001")
    book.set_title("Minimal Document")
    book.set_language("en")
    book.add_author("Test Author")

    c1 = epub.EpubHtml(title="Content", file_name="content.xhtml", lang="en")
    c1.content = """<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Content</title></head>
<body>
<h1>Minimal Document</h1>
<p>This is a minimal EPUB generated by ebooklib.</p>
</body>
</html>"""
    book.add_item(c1)

    book.toc = [epub.Link("content.xhtml", "Content", "content")]
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = ["nav", c1]

    path = os.path.join(output_dir, "ebooklib-minimal.epub")
    epub.write_epub(path, book)
    return path


def create_complex_structure(output_dir):
    """EPUB with nested TOC, multiple sections, and rich metadata."""
    book = epub.EpubBook()
    book.set_identifier("urn:uuid:ebooklib-complex-001")
    book.set_title("Complex Structure Test")
    book.set_language("en")
    book.add_author("First Author")
    book.add_author("Second Author")
    book.add_metadata("DC", "description", "A complex structure test with nested TOC.")
    book.add_metadata("DC", "publisher", "Test Publisher")
    book.add_metadata("DC", "rights", "Public Domain")
    book.add_metadata("DC", "subject", "Testing")
    book.add_metadata("DC", "date", "2025-01-01")

    style = epub.EpubItem(
        uid="style",
        file_name="style/main.css",
        media_type="text/css",
        content=b"body { font-family: Georgia, serif; margin: 2em; }\n"
        b"h1, h2, h3 { color: #333; }\n"
        b"table { border-collapse: collapse; width: 100%; }\n"
        b"th, td { border: 1px solid #ddd; padding: 8px; }\n",
    )
    book.add_item(style)

    # Part 1
    p1c1 = epub.EpubHtml(title="Chapter 1", file_name="ch01.xhtml", lang="en")
    p1c1.content = """<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Chapter 1</title><link rel="stylesheet" href="style/main.css" type="text/css"/></head>
<body>
<h1>Part I: Fundamentals</h1>
<h2>Chapter 1: Getting Started</h2>
<p>This chapter introduces the fundamental concepts.</p>
<h3>Section 1.1</h3>
<p>A subsection with <em>emphasis</em> and <strong>strong</strong> text.</p>
<h3>Section 1.2</h3>
<p>Another subsection with a nested list:</p>
<ul>
<li>Level 1
  <ul>
  <li>Level 2a</li>
  <li>Level 2b
    <ul><li>Level 3</li></ul>
  </li>
  </ul>
</li>
<li>Another level 1</li>
</ul>
</body>
</html>"""
    p1c1.add_item(style)
    book.add_item(p1c1)

    p1c2 = epub.EpubHtml(title="Chapter 2", file_name="ch02.xhtml", lang="en")
    p1c2.content = """<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Chapter 2</title><link rel="stylesheet" href="style/main.css" type="text/css"/></head>
<body>
<h2>Chapter 2: Data Structures</h2>
<table>
<thead><tr><th>Structure</th><th>Access</th><th>Insert</th><th>Delete</th></tr></thead>
<tbody>
<tr><td>Array</td><td>O(1)</td><td>O(n)</td><td>O(n)</td></tr>
<tr><td>Linked List</td><td>O(n)</td><td>O(1)</td><td>O(1)</td></tr>
<tr><td>Hash Table</td><td>O(1)</td><td>O(1)</td><td>O(1)</td></tr>
</tbody>
</table>
</body>
</html>"""
    p1c2.add_item(style)
    book.add_item(p1c2)

    # Part 2
    p2c1 = epub.EpubHtml(title="Chapter 3", file_name="ch03.xhtml", lang="en")
    p2c1.content = """<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Chapter 3</title><link rel="stylesheet" href="style/main.css" type="text/css"/></head>
<body>
<h1>Part II: Advanced Topics</h1>
<h2>Chapter 3: Special Characters</h2>
<p>HTML entities: &amp; &lt; &gt; &quot;</p>
<p>Unicode: em dash \u2014 en dash \u2013 ellipsis \u2026</p>
<p>Symbols: \u00a9 \u2122 \u00ae \u00b1 \u2260 \u2264 \u2265</p>
</body>
</html>"""
    p2c1.add_item(style)
    book.add_item(p2c1)

    p2c2 = epub.EpubHtml(title="Conclusion", file_name="conclusion.xhtml", lang="en")
    p2c2.content = """<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Conclusion</title><link rel="stylesheet" href="style/main.css" type="text/css"/></head>
<body>
<h2>Conclusion</h2>
<p>This complex document tested nested TOC, subdirectories, tables, and rich metadata.</p>
</body>
</html>"""
    p2c2.add_item(style)
    book.add_item(p2c2)

    # Nested TOC
    book.toc = [
        (epub.Section("Part I: Fundamentals"), [
            epub.Link("ch01.xhtml", "Chapter 1: Getting Started", "ch01"),
            epub.Link("ch02.xhtml", "Chapter 2: Data Structures", "ch02"),
        ]),
        (epub.Section("Part II: Advanced Topics"), [
            epub.Link("ch03.xhtml", "Chapter 3: Special Characters", "ch03"),
            epub.Link("conclusion.xhtml", "Conclusion", "conclusion"),
        ]),
    ]
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = ["nav", p1c1, p1c2, p2c1, p2c2]

    path = os.path.join(output_dir, "ebooklib-complex-structure.epub")
    epub.write_epub(path, book)
    return path


def create_semantic_html5(output_dir):
    """EPUB with HTML5 semantic elements."""
    book = epub.EpubBook()
    book.set_identifier("urn:uuid:ebooklib-semantic-001")
    book.set_title("Semantic HTML5 Content")
    book.set_language("en")
    book.add_author("Test Author")

    c1 = epub.EpubHtml(title="Semantic Content", file_name="semantic.xhtml", lang="en")
    c1.content = """<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head><title>Semantic Content</title></head>
<body>
<section epub:type="chapter">
<h1>Semantic HTML5 Content</h1>
<article>
<header>
<h2>Article Title</h2>
<p>Published on <time datetime="2025-01-15">January 15, 2025</time></p>
</header>
<p>This article uses HTML5 semantic elements including
<mark>highlighted text</mark>, <small>small print</small>,
and <abbr title="Electronic Publication">EPUB</abbr>.</p>
<aside>
<p>This is a sidebar with supplementary content.</p>
</aside>
<figure>
<figcaption>A code example</figcaption>
</figure>
<footer>
<p>Article footer with <cite>citation</cite> information.</p>
</footer>
</article>
<section>
<h2>Additional Section</h2>
<details>
<summary>Click to expand</summary>
<p>This is expandable content inside a details element.</p>
</details>
<p>Inline elements: <kbd>Ctrl+C</kbd>, <var>x</var>, <samp>output</samp>,
x<sup>2</sup> + y<sub>1</sub></p>
</section>
</section>
</body>
</html>"""
    book.add_item(c1)

    book.toc = [epub.Link("semantic.xhtml", "Semantic Content", "semantic")]
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = ["nav", c1]

    path = os.path.join(output_dir, "ebooklib-semantic-html5.epub")
    epub.write_epub(path, book)
    return path


def main():
    output_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "epubs"
    )
    os.makedirs(output_dir, exist_ok=True)

    generators = [
        ("basic-prose", create_basic_prose),
        ("multilingual", create_multilingual),
        ("minimal", create_minimal),
        ("complex-structure", create_complex_structure),
        ("semantic-html5", create_semantic_html5),
    ]

    print("--- ebooklib EPUBs ---")
    total = 0
    failed = 0
    for name, gen_func in generators:
        total += 1
        try:
            path = gen_func(output_dir)
            size = os.path.getsize(path)
            print(f"  [{total}] ebooklib: ebooklib-{name}... OK ({size // 1024}KB)")
        except Exception as e:
            print(f"  [{total}] ebooklib: ebooklib-{name}... FAIL ({e})")
            failed += 1

    print()
    print(f"  Total: {total}, Succeeded: {total - failed}, Failed: {failed}")
    return 1 if failed > 0 else 0


if __name__ == "__main__":
    sys.exit(main())
